title: '开源之书 · 共读'

menu:
  main:
    - name: "共读活动"
      url: "/events/"
      weight: 10
    - name: "书单"
      url: "/books/"
      weight: 20
    - name: "关于"
      url: "/about/"
      weight: 30
    - name: "文章"
      url: "/posts/"
      weight: 40
baseURL: 'https://osbook.opensourceway.blog/'

# Hugo Blox module import
module:
  hugoVersion:
    min: '0.128.0'
  imports:
    - path: github.com/HugoBlox/kit/modules/blox
      mounts:
        - source: layouts
          target: layouts
        - source: static
          target: static
        - source: assets
          target: assets
        - source: i18n
          target: i18n
        - source: data
          target: data
        - source: archetypes
          target: archetypes
        - source: assets/vendor
          target: assets/vendor
        - source: layouts/_partials/hbx
          target: layouts/_partials/hbx

defaultContentLanguage: zh
hasCJKLanguage: true
defaultContentLanguageInSubdir: false

cascade:
  - target:
      path: /books/**
      kind: page
    show_date: true
    share: true
    pager: true

  - target:
      path: /events/**
      kind: page
    show_date: true
    share: true
    pager: true

  - target:
      path: /posts/**
      kind: page
    pager: true
    show_date: true
    show_date_updated: true
    reading_time: true
    commentable: true
    show_related: true
    share: true
    show_breadcrumb: false

outputs:
  home: [HTML, RSS]
  section: [HTML, RSS]

build:
  writeStats: true
summaryLength: 30
pagination:
  pagerSize: 12
enableEmoji: true
enableRobotsTXT: true
imaging:
  resampleFilter: lanczos
  quality: 90
  anchor: smart

taxonomies:
  author: authors
  tag: tags
  category: categories

related:
  threshold: 80
  includeNewer: true
  indices:
    - name: tags
      weight: 100
    - name: categories
      weight: 70

markup:
  _merge: deep
security:
  _merge: deep
